### ISSUE TITLE
Providing DICOM metadata from Workflow Usage.

### ISSUE THREAD

**Issue by JJFinnerty** [Project-MONAI/monai-deploy-workflow-manager#114]
Parent Ticket #96 
To support the Workflow manger's ability to have conditional workflows we need to be able to expose the DICOM metadata dictionary.  This is Json files saved at the series and study level of the DICOM folder structures.

These file need to be loaded into a Dictionaries, and have appropriate methods exposed for access data from the Series And data from the Study.

This DICOM Data can be address either by the DICOM TAG ‘(0018,0050)’ or the DICOM TAG Name ‘SliceThickness’

## Folder structure ##

The following structure should be used within MinIO:
```
BUCKET
- {{PAYLOAD_ID}}
-- dcm
--- series1
--- series2
```

## File Structure ##
- To be confirmed by Victor.

## Acceptance criteria ##
1. GIVEN that the DICOM meta data Json files exist WHEN parsed THEN this should create the required data dictionaries.
2. GIVEN that the DICOM meta data has been parsed WHEN a TAG/NAME is requested which exist within the Data THEN the string should be returned.
3. GIVEN that the DICOM meta data has been parsed WHEN a TAG/NAME is requested which doesn't exist within the Data THEN A NULL should be returned.

**Comment by jackschofield23** [comment]
Notes:
inside series,
there is image file 
and metadata json file

id-.dcm.json

for metadata file, either 

we store dicom tags as "0000", "0000". They are stored without comma in json file.

Any

grab first json file from first series and look for the tag. 
If tag doesn't exist, go to the next series etc, until one is found. 
If nothing found return null.

All
If its not found in any, return null

**Comment by lillie-dae** [comment]
**Example Tags**

context.dicom.series.any('0010','0040') 
first series folder has a null look at series 2 if it has a value use that.
no value 'null'

context.dicom.series.all('0010','0040')  'null' ""
value has to be same across all series. if its not return null if it is return value.
if first is a null break out loop and return null.

**Comment by mocsharp** [comment]
@lillie-dae can we close this as complete?

**Comment by jackschofield23** [comment]
Closed
