### ISSUE TITLE
TEST - Update Task Status integration tests

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#115]
The followng issues have been found: 

Test: Publish an invalid Task Update event which does not update the task status
- Missing Status sets TaskStatus to Unknown

~~Test: Publish an valid Task Update event with a status that is invalid for current status~~
~~- Status is set back to Accepted from Succeeded~~
~~- Status is set back to Accepted from Failed~~
~~- Status is set back to Accepted from Canceled~~ These have been completed

**Comment by RemakingEden** [comment]
Missing Status sets TaskStatus to Unknown

Discussed with @JoeBatt1989 & @jackschofield23 and the above test is no longer as the unknown status will be removed. I will remove the test in this ticket.
