### ISSUE TITLE
TEST - Task destination integration tests

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#119]
1. Task returns succeeded w/ task destination, single task dispatched, WFI is updated with new task - Done
2. Task returns succeeded w/ task destination, multi tasks dispatched, WFI is updated with new tasks - Done
3. WFI already exists with Task as Dispatched and get an update, shouldnt get dispatched - Done
4. WFI already exists with Task as Accepted and get an update, shouldnt get dispatched - Done
5. WFI already exists with Task as Completed and get an update, shouldnt get dispatched - Done
6. WFI already exists with Task as Created and get an update, should get dispatched - Covered by tests 1 and 2
7. WF exists wth multi tasks and Task returns succeeded w/o task destination, no task is dispatched and WFI status not updated - Done - **Issue found - status gets set as Success**
8. WF exists with single Task and Task returns succeeded w/o task destination, no task is dispatched and WFI status is updated -- Done - added to Task Status update tests - ~~**Issue found - Canceled does not set WFI status to Succeeded. Failed does not set WFI status to Failed**~~ Done
9. Task returns failed w/ task destination, single task is not dispatched, WFI status is updated - Done - ~~**Issue Found - Same as 8**~~ Done
10. Task ID does not exist in WF - Done - ~~**Issue Found - Status of WFI instance is set to Succeeded** - this requires discussion as if its needed. How would you get in a situation where a task was referencing another task which did not exist in the WF? ~~ Done
11. WF not found -Done - Already existing in Task Status

**Comment by mocsharp** [comment]
@JoeBatt1989 can we close this as complete?

**Comment by RemakingEden** [comment]
Looking into this ticket now

**Comment by RemakingEden** [comment]
All tests are unignored and appear to be passing so this ticket can be moved to done.
