### ISSUE TITLE
### Tests - Post evaluators - conditional execution - Integration Tests

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#144]
### Tests
- Task destination with condition true, WFI is updated with Task and task dispatch message is published ("true" == "true")
- Task destination with condition false, WFI is not updated with Task and task dispatch message is not published ("true" == "false")
- Multiple task destinations with condition true, multiple task dispatch messages sent
- Multiple task destinations with condition false, no task dispatch messages sent
- Multiple task destinations one with condition true and one with false, 1 task dispatch message published for task which is true
- Workflow instance status remains created when any task status is either dispatch or accepted
- Workflow instance status is succeeded when there are no more tasks to run, all succeeded, or tasks in a running status (Accepted or Dispatched)
- Workflow instance status is failed when a condition is invalid

_Originally posted by @RemakingEden in https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/96#issuecomment-1134706293_

**Comment by RemakingEden** [comment]
Blocked due to issue https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/147
