### ISSUE TITLE
Task Destination Condition evaluating to true when invalid

### ISSUE THREAD

**Issue by DuncanSangster** [Project-MONAI/monai-deploy-workflow-manager#147]
### Description
Using an invalid condition in the TaskDestination evaluates to true, causing the associated task to be published and the Workflow Instance Status to remain at Created

### Steps to reproduce
Pass through an invalid condition into TaskDestination e.g. "'invalid'>'false'"

### Expected behavior
No Task Dispatch message should be sent
Workflow Instance Status should be set to Failed

**Comment by lillie-dae** [comment]
@DuncanSangster @elleyouseewhy @joshliberty @JJFinnerty 
Does this task need closing?

**Comment by RemakingEden** [comment]
This is now working correctly, the bug has been fixed
