### ISSUE TITLE
TEST -  handle task artifacts - workflow executer Integration Tests

### ISSUE THREAD

**Issue by jackschofield23** [Project-MONAI/monai-deploy-workflow-manager#158]
Int tests for https://github.com/Project-MONAI/monai-deploy-workflow-manager/pull/131

Int tests to cover WorkflowRequestMessage and TaskDispatchEvent. 
int tests to cover TaskUpdateEvent output dir or artefacts exists

WorkflowRevisions specify the inputs and mandatory flag.

input types that testing 
- context.input 
- context.executions.TASK_ID.artifacts.ARTIFACT_NAME
- context.executions.TASK_ID.output_dir

Dev to be updated to: 
- context.input to be changed to context.input.dicom
- mandatory to be true by default

1. WorkflowRevision created with 1 Task with context.input with flag mandatory and folder exists in minio. WorkflowRequestMessage generated. TaskDispatch with reference to payload folder in minio

@JoeBatt1989 to create a test matrix

**Comment by RemakingEden** [comment]
Test matrix https://docs.google.com/spreadsheets/d/1ohYtCKHc5911SDSH0gJDCDrotRVnk2KmgcCsxYAPK0U/edit
