### ISSUE TITLE
TEST - Metadata store: Plugin - Argo - Integration Tests

### ISSUE THREAD

**Issue by jackschofield23** [Project-MONAI/monai-deploy-workflow-manager#160]
Int Tests for #125 

2 branches to this. 

1. WorkflowExecutor integration tests which test the metadata consumption on the TaskUpdateEvent
2. TaskExecutor integration tests to check that the metadata.json is included in a TaskUpdateEvent after consuming a TaskCallbackEvent

**Comment by mocsharp** [comment]
@elleyouseewhy can we close this as complete?
