### ISSUE TITLE
 TEST - handle task artifacts - task executer Integration Tests

### ISSUE THREAD

**Issue by jackschofield23** [Project-MONAI/monai-deploy-workflow-manager#162]
Integration Tests for #129 

- Sending artifacts on TaskDispatchEvents. 
- TaskUpdateEvent includes relative path

**Comment by RemakingEden** [comment]
Int tests:
- Send task dispatch message with artefact
- Receive task update event with same artefact

Data:
- Correct artefact (Happy path)
- Null

**Comment by JoeBatt1989** [comment]
All TaskDispatch and TaskCallback events used in test include Inputs and Outputs respectively. Moving to done
