### ISSUE TITLE
TEST - Generate temporary credentials (Links to #52) #112 #149

### ISSUE THREAD

**Issue by lillie-dae** [Project-MONAI/monai-deploy-workflow-manager#163]
Links to issue #112 
and Task #149

**Comment by RemakingEden** [comment]
Need a test plugin to test. As the credentials are added and then the task sent straight to Argo.

**Comment by RemakingEden** [comment]
There is a basic test to check that the credentials are not null. I will leave this in to do as we need to add a test to see if those credentials can successfully unlock minio.

**Comment by mocsharp** [comment]
@RemakingEden is this complete? can we close?

**Comment by RemakingEden** [comment]
Closing as these tests are duplicated in this ticket https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/302
