### ISSUE TITLE
Update workflow specification document in accordance to implementation

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#169]
A number of changes came up during development, which means that the workflow specification language had to change. The documentation should be dated accordingly.

Some specific areas that need updating:
* Parameters
* The json examples
* Export tasks
* Task templates not being available

**Comment by mocsharp** [comment]
@joshliberty can we close this as complete?

**Comment by jackschofield23** [comment]
This has been done.
