### ISSUE TITLE
Log task completions

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#170]
It is important that the workflow manager provides visibility of tasks having completed. These should be logged where they can be collected by external log aggregation systems.

**Requirements**

1. In order for logs to be easily digestible by log aggregation solutions such as logstash, the workflow manager should output logs in a structured format such as json.
2. Logs should contain any relevant information about the event that has happened (see table below)

**Required events**
At the very least, the following events should be logged:

_Task completed_
Required data points:

- Execution ID
- Task ID
- Workflow ID
- Correlation ID
- Task status
- Task type
- The task execution stats object
- Patient Name
- Patient DOB
- Patient ID
- Task start time
- Task end time

**Comment by mocsharp** [comment]
@lillie-dae , can we close this as complete?

**Comment by mocsharp** [comment]
Closing as complete
