### ISSUE TITLE
CI pipeline changes

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#173]
The following changes need to be made to the CI pipeline: 

- [x] Any stages can fail and can still merge. Failures should be a hard block for merging. Need to speak to David or Josh - https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule
- [x] Do integration tests contribute to codecov - if not they should be. - Codecov will remain at 70% for now. We can reduce it later if it becomes an issue. This is within our gift to do through sonarcloud
- [ ] Review sonarcloud rules and use of sonarlint locally - are they all required? We need a process put in place for people to review sonarcloud issues. Training docs required.
- [ ] Review code scanning alerts - https://github.com/Project-MONAI/monai-deploy-workflow-manager/security/code-scanning
- [x] Use of dependabot? 
- [ ] Trigger for publishing to Github CR and Docker Hub.

**Comment by RemakingEden** [comment]
Any stages can fail and can still merge. Failures should be a hard block for merging. Need to speak to David or Josh - https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule - **This has now been resolved for everything apart from Sonar**

 Do integration tests contribute to codecov - if not they should be. - Codecov will remain at 70% for now. We can reduce it later if it becomes an issue. This is within our gift to do through sonarcloud - **The codecov issue has been resolved and it is now measuring just new code. Most people are getting over 70% cov. We cannot add int tests to coverage as it seems there is no way to do this** 

 Review sonarcloud rules and use of sonarlint locally - are they all required? We need a process put in place for people to review sonarcloud issues. Training docs required. - **This still needs to be reviewed, I have added sonarlint files but we need to go through and disable uneeded alerts**

 Use of dependabot? - **Dependabot is now added**
