### ISSUE TITLE
Save patient details in database

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#174]
As part of ingesting payloads due to a workflow request, patient details need to be extracted and saved alongside the payload object in the database.

This should be done in accordance to the data type that has been received in the workflow request. For example, when the input type is DICOM the information should be retrieved from the relevant DICOM tags.

**Required data points**

- Patient ID
- Patient name
- Patient sex
- Date of birth

- [ ] #211

**Comment by joshliberty** [comment]
@jackschofield23 @JJFinnerty we also need to expose the patient information as part of the workflow context object for use in parameters and conditional statements (see #179). Do you want to do that as part of this ticket or should I create a new ticket?

**Comment by jackschofield23** [comment]
Might be worth keeping these tickets simple and creating a new ticket for that work.

**Comment by mocsharp** [comment]
@jackschofield23 can we close this as complete?

**Comment by mocsharp** [comment]
Closing as complete
