### ISSUE TITLE
Implement awaitable Storage Service 

### ISSUE THREAD

**Issue by lillie-dae** [Project-MONAI/monai-deploy-workflow-manager#177]
Current implementation of storage service get objects requires callback events makes it impossible to unit test.
Can we implement an awaitable version in the storage service?

**Comment by mocsharp** [comment]
What do you mean by impossible to unit test? What's the use case?

**Comment by mocsharp** [comment]
@lillie-dae @jackschofield23  is this done?

**Comment by jackschofield23** [comment]
This has been done yes.
