### ISSUE TITLE
Advanced validation

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#186]
Some ideas:
* Check that variable strings are syntactically valid
* Check that variables reference real objects
* Check that referenced artifacts are generated somewhere
* Check that referenced plugins are actually available
* Bonus: Allow plugins to validate their own tasks (argo plugin will check that workflows exist, etc)

**Comment by woodheadio** [comment]
I believe that the last work on workflow validation was covered in this PR: https://github.com/Project-MONAI/monai-deploy-workflow-manager/pull/632. I am going to close this off as done.
