### ISSUE TITLE
Argo plugin - support workflow parameters in 'args' object

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#187]
Argo supports passing parameters dynamically when executing workflows (see https://stackoverflow.com/a/69362188). We should allow workflow builders to make use of this, and provide parameters by specifying either hardcoded values or workflow variables as parameters.

### Example
```
"args": {
    ....
    "parameters": {
       "parameter_one": PARAMETER_ONE_VALUE,
       "parameter_two": {{ context.executions.some_execution.result.my_variable }}

    }
}
```

### Acceptance criteria

- GIVEN an Argo task is defined in the workflow specification and includes a workflow parameter, WHEN the Argo workflow is submitted THEN it is provided with the parameter 
- GIVEN a workflow parameter of a task contains a variable string, WHEN the task is submitted THEN the variable is evaluated and converted to its value before being sent to the Argo plug-in

**Comment by mocsharp** [comment]
@lillie-dae  can this be closed? do we have an integration test for this?
