### ISSUE TITLE
Implement task timeouts

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#191]
Currently, once a task is launched using a plug-in (for example an Argo workflow is submitted) the workflow is paused until a response is received with the task callback event. This means that if Argo crashes, or anything else happens, and no response is ever received the workflow will be stalled and will never resume.

To mitigate that, we should implement task timeouts with the future work of retries planned in https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/193. Whenever a task takes longer than the timeout, it can then be marked as failed or retried.

### Workflow spec
task timeouts will be defined with two new fields on the task object in the workflow spec:

1. **timeout_minutes**: integer, the number of minutes this task should take at most
2. **timeout_retries**: integer, the number of times this task should be retried after timeouts (only used in https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/193)

### Acceptance criteria

1. GIVEN a task has a timeout value WHEN the specified time has passed AND the task is still not complete THEN the task should be marked as timed out
2. WHEN a task has no timeout value THEN a configurable default value should apply
3. GIVEN a task has timed out WHEN the task completes THEN it should remain failed even if the task finished successfully.

### Implementation notes
![image](https://user-images.githubusercontent.com/1472923/176702392-be511abd-5171-4eb9-af4f-bd0223053cc3.png)

- To be implemented as a cron job which looks at all submitted tasks and how long ago they were submitted. This job can run at a configurable interval.
- Task plug-ins should be given the opportunity to cancel tasks gracefully.
- Timeouts should also apply to export tasks

**Comment by lillie-dae** [comment]
Need to add 
- timeout **interval** and 
- timeout **retries**

to workflow spec and update docs. I think task level?

defaultTaskTimeout in appsettings

Needs to happen on Task Manager Level.

### Task Manager
Cron Job - timeout

- [ ] - Endpoint it can poke?
- [ ] - Quartz.NET / nCron ?
- [x] - Background service

cronjob interval how often it runs in appsettings 1minute

### Whats cron/endpoint doing?
Fail current task spawn new task (append to name "_retry{count}"). 
cancel any running argo workflows and submit argo request to run it again.
if task has not completed after all retries counts fail task
When we fails (max retries) TaskUpdate workflow manager workflow 
-> poke argo to cancel it. (Argo terminate vs stop - choose terminate)
(implent genericly plugin forceCanceTask, retryTaskCode)



### Where does polly fit it?
Attach it to httpclients and put in appSettings polly settings.


Timeouts should also apply to export tasks -> to be split out into new story.

**Comment by mocsharp** [comment]
@lillie-dae can this be closed?
