### ISSUE TITLE
Miscellaneous API fixes

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#199]
As many APIs were built before we had the time to refine them properly, we now need to implement a few minor changes.

- [x] Workflow instances should be filterable by status
- [x] The payload API response schema should include the IDs of workflow instances triggered by this payload
- [x] it should be possible to filter payloads by patient ID and/or name
- [x] list APIs should be sorted by timestamp (received time for payloads, start time for workflow instances)

**Comment by mocsharp** [comment]
@lillie-dae can this be closed?
