### ISSUE TITLE
Add patient age and hospital ID

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#203]
We currently have patient ID and date of birth in the patient details object. These fields don't always exists – sometimes the patient is identified using the hospital ID tag, and sometimes only the age is available.

We should include hospital ID and age in the patient details object, so that if a patient ID/date of birth doesn't exist the client can use these instead.

**Comment by jackschofield23** [comment]
@DanielNuttall-AD @joshliberty This has been merged under the assumption that hospital Id is (0010,0021) Issuer of Patient ID. If this is something else we can create a new ticket to change.
