### ISSUE TITLE
Separate Task Manager & Workflow Manager

### ISSUE THREAD

**Issue by mocsharp** [Project-MONAI/monai-deploy-workflow-manager#243]
**Is your feature request related to a problem? Please describe.**
To support the deployment of multiple instances of Task Manager on multiple environments, e.g. cloud, on-prem, and hybrid, TM & WM should be separated.

**Describe the solution you'd like**
Provide two packages, one for WM and another for TM.

**Comment by mocsharp** [comment]
@jackschofield23 can we close this? 

#291

**Comment by jackschofield23** [comment]
Yes this has been done
