### ISSUE TITLE
Test - Workflow Update Schema Change

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#270]
On this PR https://github.com/Project-MONAI/monai-deploy-workflow-manager/pull/251 there are the following tests failing so they have been commented out. It looks as though the workflow update schema has changed. These tests need fixing or bugs raising on the development code. 
- WorkflowApi.feature 
  - Update workflow with invalid details (Test 1 commented out) 
- WorkflowApi.feature 
  - Update workflow where workflow ID does not exist
- WorkflowApi.feature 
  - Delete a workflow and recieve 404 when trying to UPDATE by ID

**Comment by RemakingEden** [comment]
Fixed in commit [c95b46c](https://github.com/Project-MONAI/monai-deploy-workflow-manager/pull/251/commits/c95b46c821d73a92f0d7732d07a150fbbacb24ef)
