### ISSUE TITLE
Bug. silent fail during Create Temp Credentials

### ISSUE THREAD

**Issue by neildsouth** [Project-MONAI/monai-deploy-workflow-manager#295]
### Description
upon creating storage credentials, the external mc.exe program is invoked and an `Alias` is made called serviceName (or something similar can be set in config) if the Alias exists already, but has incorrect values (wrong url). the call to make temporary credentials silently fails ! 

### Steps to reproduce
Please share a clear and concise description of the problem.
1. using mc.exe make an alias called serviceName but with incorrect url.
2. trigger the workflow locally (follow mwm-developer-setup.md) 

### Expected behavior
This should at the very least produce an error log

### Actual behavior
It silently fails !

**Comment by lillie-dae** [comment]
@neildsouth
Attempted to recreate this issue was unable too. You can see error logging in picture below.

![image](https://user-images.githubusercontent.com/61380713/185616216-4bd29604-cccd-4404-9db4-157f0faa0b23.png)

**Comment by lillie-dae** [comment]
while we still couldn't recreate issue neil and myself discussed and made a change to storage module version in 0.2.5 that should remove this bug from even being possible by setting correct alias every time.

Moved to closed and done.
