### ISSUE TITLE
Task Dispatch messages currently getting deleted from Mongo

### ISSUE THREAD

**Issue by jackschofield23** [Project-MONAI/monai-deploy-workflow-manager#300]
### Description

Links to https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/196

Task dispatch messages are getting deleted from MongoDB after the task callback has been received. We should not delete them and only update with the necessary information.

**Comment by mocsharp** [comment]
@jackschofield23 you've fixed this right?

**Comment by jackschofield23** [comment]
> @jackschofield23 you've fixed this in #314 right?

Yeah that's right!
