### ISSUE TITLE
TEST - TaskManager test plugin

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#306]
Add tests to cover the following: 
- Creating an TaskDispatch against the test plugin for TaskCallback with status Succeeded
- Creating an TaskDispatch against the test plugin for TaskCallback with status Failed
- Creating an TaskDispatch against the test plugin for TaskCallback with further metadata

**Comment by RemakingEden** [comment]
Is this not now covered in the clinical review tests?

**Comment by RemakingEden** [comment]
The clinical review tests now cover most of this. What they dont cover is the generation of the task callback however this is created by the plugin and by testing this with the test plugin we would only be testing the test plugin and nothing else. We would not know that Argo etc would work correctly.

The above tests will be covered manually or automated in an end to end test
