### ISSUE TITLE
When the payload patient data has no data, most fields show empty string and not null

### ISSUE THREAD

**Issue by RemakingEden** [Project-MONAI/monai-deploy-workflow-manager#320]
### Description
Currently when a payload missing data is created it puts every field apart from DOB as an empty string. From talks with @joshliberty it seems these should all be null.

![image](https://user-images.githubusercontent.com/12913562/184367336-bda555f2-3be4-446e-a787-07a2f9e2cb1d.png)

### Expected behavior
All patient details in payload resolve as null if empty

### Actual behavior
Everything apart from DOB resolve as empty string aka ""

**Comment by RemakingEden** [comment]
Ive commented two tests out for this that need to be added back in when the work is done. You can find them by searching for the url of this bug.

**Comment by jackschofield23** [comment]
If we are checking for null or empty string is this a bug?

**Comment by mocsharp** [comment]
Are you referring to a payload without any files? If so, IG makes sure payloads always contain at least one file.  In addition, I think WM can just ignore the workflow request if no files are included.
