### ISSUE TITLE
Support conditional chaining

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#36]
Adding to chaining as described here: https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/35.
The workload manager should support _conditional_ chaining - so that the output of an application can be evaluated to determine whether and which application should be executed next.

**User Story**
As a system administrator, I want to be able to define conditions that will determine application chaining, so that I can define a whole clinical workflow and execute the relevant applications based on the data.

**Acceptance criteria**
* GIVEN an application finished execution THEN its output data can be evaluated and determine the next application
* GIVEN an application finished execution THEN its output data can be evaluated and determine the output sink

**Comment by JHancox** [comment]
Agree that this makes sense - this is what I was referring to as 'conditional evaluators', which could also incorporate what we talked about as 'connectors'
