### ISSUE TITLE
/workflow endpoint requires all objects even if they are null

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#381]
### Description
When posting json to the /workflows endpoint it seems that the request requires you to have all objects in there even if they are null. Issues I have seen are below but there may be more: 

- tasks.artifacts.outputs must be specified but is acceptable when an empty array - Joss - Should allow nullable
- Informatics.dataOrigins must be present...is this always the case? Especially as we are setting MIG rejectUnknownSources to false - Joss - Should allow nullable
- tasks.exportDestinations.conditions must be specified but can be an empty string - Joss - Should allow nullable
- tasks.args must be must be specified - Joss - Should allow nullable

These scenarios need to be discussed as they may be by design. If thye arent the the schema requires up updating and integration tests creating.

**Comment by RemakingEden** [comment]
After speaking to @jackschofield23  these all appear valid and validation should succeed with null to all these values. We will need to recheck the tests after the dev work has been done.
