### ISSUE TITLE
Export task does not support folders

### ISSUE THREAD

**Issue by jackschofield23** [Project-MONAI/monai-deploy-workflow-manager#387]
### Description
Currently the export message takes a list of files. We will need to determine if a given value is a folder and then get all .dcm files within that folder and subfolders. 

### Expected behavior
The export should support folders

### Actual behavior
the export fails within the MIG when folders are sent.

**Comment by mocsharp** [comment]
@jackschofield23 are you getting the list of files based on the rules provided by the user in the workflow definition, or are you fixing it to `.dcm` files?

Just a side note, MIG supports data other than `dcm`, it could also be uploading `json`, `xml` for HL7 and FHIR.
