### ISSUE TITLE
Monai Deploy End to End Test Execution

### ISSUE THREAD

**Issue by JoeBatt1989** [Project-MONAI/monai-deploy-workflow-manager#409]
**Is your feature request related to a problem? Please describe.**
Running suite of E2E tests against MONAI Deploy.

**Describe the solution you'd like**
Manual testing of real life secenarios. 
Test scenarios - https://docs.google.com/spreadsheets/d/1zGSbKd0kpf7Fd0QyDi40tvR54uC0g4NhEl5PqS4TBJQ/edit?usp=sharing
Test data - https://drive.google.com/drive/folders/11vxyZOAUmEuTtIxJxGJ8oAMFnjZtXwV3?usp=sharing

**Comment by dbericat** [comment]
I am good having this here for tracking within clinical data pipelines for now. 

But once done, let's move them to e2e-testing at the monai-deploy parent repo (similar to performance-testing).

**Comment by woodheadio** [comment]
Closing this one down, as this has been done and the e2e tests have been added to the parent repo as suggested [here].(https://github.com/Project-MONAI/monai-deploy/tree/main/e2e-testing)
