### ISSUE TITLE
Payloads API

### ISSUE THREAD

**Issue by mocsharp** [Project-MONAI/monai-deploy-workflow-manager#44]
As an MWM integration and IG ACR API user, I would like to be able to query the status of the workflow that is triggered with the dataset received by IG and passed to MWM, so that my applications can easily check the status of the executions.

It should be possible to retrieve a list of workflow requests (payloads), as well as a specific one by payload ID.

Required data points:

1. Payload identifier
2. Triggered workflow instance identifiers
3. Patient information

**Implementation notes**
In order for this to be possible, we need to create a new collection in MongoDB where we store information about received payloads. Workflow instances should reference those payload objects.

- [x] #212

**Comment by joshliberty** [comment]
@jackschofield23 if this is done, what schema did you use for a response?

**Comment by mocsharp** [comment]
@jackschofield23 can we close this issue as complete?

**Comment by jackschofield23** [comment]
Closed
