### ISSUE TITLE
API Authentication Layer

### ISSUE THREAD

**Issue by dbericat** [Project-MONAI/monai-deploy-workflow-manager#46]
APIs should authenticate & authorise users before granting access to any API endpoinds.
We should have at least two roles - admin and user.

Users should be able to use read-only APIs (eg Tasks API, Payloads API, Workflow Instances API, etc). Admins should also be allowed to use write/update APIs such as the Workflows API.

* It should be possible to configure an OAuth2 provider URL in the configuration file
* It should be possible to configure the token claim that gives access to Admin APIs, and what claim gives access to the read APIs (mapping external roles/properties to our "admin"/"user" roles).

Note: check with Joe about what to do around test bypass.

**Comment by dbericat** [comment]
TODO:  add security section to requirements

**Comment by elleyouseewhy** [comment]
https://dev-aide.answerdigital.io:8443/auth/realms/aide/.well-known/openid-configuration

**Comment by slbryson** [comment]
@elleyouseewhy You provided a pointer to AnsDigital OpenID configuration details.  Do you mean to suggest OpenID compliant solution that can authenticate with AnDigital is recommended?

**Comment by slbryson** [comment]
The solution should pluggable with any OpenID connect and OAuth2 compliant provider.  i.e. Keycloak is fine for E2E testing and reference implementation, but it should support other Auth providers compliant to the same standards.  
I don't see any issues with using Keycloak as a reference.

**Comment by joshliberty** [comment]
@slbryson we were talking about integrating with an OpenID provider to allow validating tokens when authenticating API requests. Lucy has just put this here as an example for the team as to what this URL is on the AIDE test environment.

**Comment by mocsharp** [comment]
Should we make this a standalone library like the storage & messaging repositoiries so it can be used by both IG & WM?

**Comment by elleyouseewhy** [comment]
From refinement: Implement Mock auth service
