### ISSUE TITLE
Metadata store:

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#50]
The Workflow manager will have the ability to store & read metadata supplied from the tasks of the clinical workflow.  This Data will be store in MongoDB for that specific workflow execution.  This metadata can then be used by the Workflow Manager's conditonal system to control the execution of further task destinations & or export desinations.

## Related Tasks ##
- [x] Workflow manger to save the task metadata & allow access to the data for the condital system. #124 
- [x] Argo Plugin to be able to handle a metadata.json Output file &  Task executor to add metadata #125

### Acceptance Criteria ###
- GIVEN a valid task update status event WHEN the metadata is availibe Then the workflow manager will update Stored metadata JSON object with the new metadata.
- GIVEN a conditional statement WHEN the statement is Parsed and the tasks metadata key is requested Then the metadata value for the key is resolved.
- GIVEN a conditional statement when the statement is Parsed and the tasks metadata key is requested but doesn't exeist Then the returned Value is Null.
- GIVEN that a task has created a metadata.json file WHEN this JSON is valid THEN when the task update status is been instantiate the metadata attribute is populated.
- GIVEN that a task has not created the metadata.json file THEN when the task update status is been instantiate the metadata attribute is left blank.
- GIVEN that a task has created a metadata.json file WHEN this JSON is invalid THEN when the task update status is been instantiate the status should be returned as Error.

**Comment by elleyouseewhy** [comment]
**ROADMAP DAYS: 2
ACTUAL DAYS:**

**Comment by mocsharp** [comment]
@lillie-dae can we close this issue as complete?

**Comment by mocsharp** [comment]
Closing as complete
