### ISSUE TITLE
Listen to new workflow request

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#51]
### Overview
New data comes into the workflow manager using an event broker. After a new payload is assembled in the Monai Informatics Gateway, information about the payload is published by the MIG onto a message queue, which the MWM needs to listen to.

The event broker adapter is also used for communication between the workflow executer and the task executer - the design needs to be generic enough so that different messages will trigger different components within the workflow manager.

The event broker needs eventually to support the following events (for information only, the only event to support at the moment is the workflow request event):

| Queue Name | Publisher | Consumer |
|------|------|------|
|md.workflow.request|Informatics Gateway|Workflow Executer
|md.workflow.task_dispatch|Workflow Executer|Task Executer
|md.workflow.task_callback|App Servers|Task Executer
|md.export.complete|Workflow Executer|Informatics Gateway

### Basic information
Queue name: md.workflow.request
Payload schema: https://github.com/Project-MONAI/monai-deploy-informatics-gateway/blob/develop/guidelines/srs.md#published-events

### Error handling

1. The payload should be validated to make sure it contains all the necessary information. In case it doesn't, or in case it's malformed in any other way, the message should be rejected and directed to a dead letter queue (reject with requeue = false).
2. In case it is not possible to handle the message for another reason, for example our database not being available - the message should be placed back in the queue (reject with requeue=true).

###  Trigger workflow manager on valid input
When receiving a valid input, the payload listener should notify the workflow manager component that the new payload has been received. The workflow manager component returning a success response to that notification should mean that the details have been persisted, and that the event can safely be ack'd.

![image](https://user-images.githubusercontent.com/1472923/157269828-03df61a6-4208-4985-8d90-955745d822ce.png)

### Acceptance criteria

1. Given a valid payload message, when a workflow instance has been created by the workflow manager component, then the event should be acknowledged and removed from the queue
2. Given a payload message, when a workflow instance couldn't be created because the database couldn't be contacted, then the event message should be returned to the queue and retried at a later stage
3. Given an invalid payload message, when it is picked up by the payload listener it should be rejected and not tried again
4. Given the handling of the message was interrupted, when it is being retried then there are no side effects from handling the message for a 2nd time.

**Comment by joshliberty** [comment]
Sequence diagram is available here: https://github.com/Project-MONAI/monai-deploy-workflow-manager/blob/main/guidelines/mwm-sadd.md#payload-listener

**Comment by mocsharp** [comment]
Created https://github.com/Project-MONAI/monai-deploy-informatics-gateway/issues/63 to include `Calling AE Title` and `Called AE Title` where applicable.

**Comment by joshliberty** [comment]
@mocsharp after thinking about this some more, I'm beginning to think that it's probably a good idea to have a single listening component which will listen to all relevant queues, and invoke the specific components (workflow manager, task manager) based on which queue an event came from.

This way we can maintain separation between implementation details (RabbitMQ) and logical handling of requests. It will make things such as triggering task callbacks using an API instead of an event much easier in the future, because wherever a request 
came in from – from the listener or from the HTTP API - will be immaterial to the task manager itself.

It will also make things easier to maintain - because there is only one listening process that can be monitored more easily.

Does that make sense?

**Comment by mocsharp** [comment]
Yes, that makes sense.
Btw, we need to enable the use of other pub-sub services.
For IG, it is through a static configuration file, at [startup](https://github.com/Project-MONAI/monai-deploy-informatics-gateway/blob/develop/src/InformaticsGateway/Program.cs), it loads the assembly dynamically. 
The interfaces are [IMessageBrokerPublisherService.cs](https://github.com/Project-MONAI/monai-deploy-informatics-gateway/blob/develop/src/Api/MessageBroker/IMessageBrokerPublisherService.cs) and [IMessageBrokerSubscriberService.cs](https://github.com/Project-MONAI/monai-deploy-informatics-gateway/blob/develop/src/Api/MessageBroker/IMessageBrokerSubscriberService.cs).

**Comment by mocsharp** [comment]
@elleyouseewhy can we close this issue as complete?

**Comment by mocsharp** [comment]
Closing as complete
