### ISSUE TITLE
Workflow delete API endpoint

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#57]
delete existing workflows so that they are no longer used

**Comment by RemakingEden** [comment]
## Delete amigos session
200 - Successful delete
400 - ID incorrect - Not a valid GUID
400 - Bad request, workflow already deleted
404 - If valid GUID but can't be found
500 - General exception like mongo being down

Do we need a flag to do hard deletes? How to implement?
Can workflows in any status be deleted?

**Comment by lillie-dae** [comment]
softdelete
No flag
All workflows and revisions
Clinician Workflows 
404 if it is deleted
Get?
Workflow instances dont get deleted

**Comment by mocsharp** [comment]
@lillie-dae can we close this issue as complete?
