### ISSUE TITLE
HTTP plugin for task runner

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#63]
Should support synchronous as well as asynchronous HTTP endpoint execution

**Comment by mocsharp** [comment]
Async HTTP call ([source](https://sequencediagram.org/index.html#initialData=MQAgwgTgpghgLlAJieIAWc4AcDOAuAegJygEcBXKAOwGMkBLGAcwhgFsA6AewiYICg49OABsoIAOo8A1gDMRXAO4gAsjCrMoEEAFoQACQAqhgAogTI8k3pV+-LDAhCa9B1Tgsu5LCGA1EsjCIAEySMvJKquqaEPaOzq7qcCAARFIQcgrKahpMWikoOJIqcU70Lm7JKSpQODia5hBcdDg8BTBFKialCZWpNXUNAIqUlAD87Z1D-NSIdg5lFUme3r6yNABGAIyyAOwghh3SUblaPeWJ7qmHOMc5MZMHJQu9SalGpuaW1lSPAILdWZ2c5LdwrHzAABi0MhAE5YSAAKIADwQEA0IhAAGUtAA3cq1fiyLjuGCKWpcNjiWRbGgABlSACUYBsNsIVENHiYsUSSXAyRSqSBZHSYAzqjYAJIAeUeABFJViANK80nk1pUgCsrRE9GQIpgNAMxkBVDmIMuyW5dkNQlx8HEhhK-AkKh0wC2ADY6QAWRCevAAZgAfNy8OZyBtdTg0LUQABqeMAKiTAHI2IgOPzbhxEPQcA44DQ0KmU4n+Nz3V7ff6g8GuuHGVA6PRcXHEyn05ns9Jc-nC8XS0nEyAoG33PwulXvX6AyGOeGRlBKEUO2mM1mjn2C-BB2X46Px3A7AouFhgfwnTp60NwxIYMIisTtGPqHAcJOhtOa3Pg07G82UCtnGr4TrarYOk8dhXn+KjhgAajAuqIA6RRUoMeQ2iIyQegAHJqMC7AyNAdOIXabjmeY7kWJbQW6sHhmAsY0NIT48Cg9r0CILJiKOyLNuQQgkiA0CtOQEAtCAWE4TAgZ+rCyAkSQIkUuJdAcQ+SFRlAdHXv+IBNiQEBtkUUD8TQgn0MJoleBJOkwfpAAyzSoSAABkIA2Dg-LuIwCBFDQJKyPQTDiUgAA6VAQOQVBUFoICKMIaAgNY44gH8dRQGwUYAJ4jEh9DBUgABy7A6fwSE4VsuE7ERIBKeI0WxfFxIxXMDlwSAADi1BaK5CBsFgPCODlIDecNeT1dAiBvowIgfh14aSlQwhzfQABecZNXFsQwQC4YogJCAZTltAABQAJQ2jQdqQQC-AAteCrKuGcpKFQChBCgZSBDdH6PcGwYfCYjFIZiwPpadRoApKCVJd9Qi-e+123QgxqmPwwPXsDB3mYJcY9nRAA8Oj7QZtRDVQJC6R6M61iGYbpSxRTkT224DiWh5vpebq0z+daMziZosxubPeChCCplzVyJXAyXefA5As38NB0FgCCIKmKMQWj938KePgPSY2MmuGPVwFi-JwErl0gDFQiYoFg1iAgRskzoOPkwWJLU7MUlG9+s4C1i4bSlQYCUlgLtQPoXBcNI4YkMLCbJuumbbVoHBO1HUCS-udgzeB9q690-CFzdOviHrMzzeIDUiTFO0gFQXDJK1Zo09WQcMyHIClczICs1uVEc1LoHJGdLcqToFDLlAV1Xnz3ehr3QuICL3ZbuLDpj0ecNy2NVtK4P0AAFbNnAUvqMg0AdMJqaMo3WjFa3WLeENThIFrMwdzXyn11PMyR0rJUBUmJOyGkuI8XEDzQO9MV7hn7qxQeoth79l3JzceIAzrQBnqMeesCGLYjEFAXAdggR-zrqRFB6cn4QCzpHaO389og2xEfHAl0KoV2LlXboANPZLggKNU+XANiH0Vv9EwJNPaGUptTJ0JMyayJ9jpcuqNeGwKXvAwWsxVypyHjmbeedhwHiwbLeW7DB44HIKrKASAv4gHYqmQIXEwpS2BItcmYhSKmTxkJUBNk1LlSgLXeq1CbD2mQiAdC9RMKdzpr+RmSC9GdlQZRdBNEhwjiwZPLg09Z6UAXrzLu2jV66JTqkzehisASygFk0xe9zHiOtizM+F8r5mhUnfUBqZlqRL1AMWJdTyG-zUZXKCdhKxaN-A2cmLYTIVLThwDO9Ds5MP3NLY8U5pl1gXCAJcK5FnkRWQw52uc6kbPHsCMZPCoJ+2AAbIAA))
[![WM-HTTP](https://user-images.githubusercontent.com/4236590/163037288-0e98c805-cef6-4292-bedd-6d4acd302e49.png)](https://sequencediagram.org/index.html?presentationMode=readOnly#initialData=MQAgwgTgpghgLlAJieIAWc4AcDOAuAegJygEcBXKAOwGMkBLGAcwhgFsA6AewiYICg49OABsoIAOo8A1gDMRXAO4gAsjCrMoEEAFoQACQAqhgAogTI8k3pV+-LDAhCa9B1Tgsu5LCGA1EsjCIAEySMvJKquqaEPaOzq7qcCAARFIQcgrKahpMWikoOJIqcU70Lm7JKSpQODia5hBcdDg8BTBFKialCZWpNXUNAIqUlAD87Z1D-NSIdg5lFUme3r6yNABGAIyyAOwghh3SUblaPeWJ7qmHOMc5MZMHJQu9SalGpuaW1lSPAILdWZ2c5LdwrHzAABi0MhAE5YSAAKIADwQEA0IhAAGUtAA3cq1fiyLjuGCKWpcNjiWRbGgABlSACUYBsNsIVENHiYsUSSXAyRSqSBZHSYAzqjYAJIAeUeABFJViANK80nk1pUgCsrRE9GQIpgNAMxkBVDmIMuyW5dkNQlx8HEhhK-AkKh0wC2ADY6QAWRCevAAZgAfNy8OZyBtdTg0LUQABqeMAKiTAHI2IgOPzbhxEPQcA44DQ0KmU4n+Nz3V7ff6g8GuuHGVA6PRcXHEyn05ns9Jc-nC8XS0nEyAoG33PwulXvX6AyGOeGRlBKEUO2mM1mjn2C-BB2X46Px3A7AouFhgfwnTp60NwxIYMIisTtGPqHAcJOhtOa3Pg07G82UCtnGr4TrarYOk8dhXn+KjhgAajAuqIA6RRUoMeQ2iIyQegAHJqMC7AyNAdOIXabjmeY7kWJbQW6sHhmAsY0NIT48Cg9r0CILJiKOyLNuQQgkiA0CtOQEAtCAWE4TAgZ+rCyAkSQIkUuJdAcQ+SFRlAdHXv+IBNiQEBtkUUD8TQgn0MJoleBJOkwfpAAyzSoSAABkIA2Dg-LuIwCBFDQJKyPQTDiUgAA6VAQOQVBUFoICKMIaAgNY44gH8dRQGwUYAJ4jEh9DBUgABy7A6fwSE4VsuE7ERIBKeI0WxfFxIxXMDlwSAADi1BaK5CBsFgPCODlIDecNeT1dAiBvowIgfh14aSlQwhzfQABecZNXFsQwQC4YogJCAZTltAABQAJQ2jQdqQQC-AAteCrKuGcpKFQChBCgZSBDdH6PcGwYfCYjFIZiwPpadRoApKCVJd9Qi-e+123QgxqmPwwPXsDB3mYJcY9nRAA8Oj7QZtRDVQJC6R6M61iGYbpSxRTkT224DiWh5vpebq0z+daMziZosxubPeChCCplzVyJXAyXefA5As38NB0FgCCIKmKMQWj938KePgPSY2MmuGPVwFi-JwErl0gDFQiYoFg1iAgRskzoOPkwWJLU7MUlG9+s4C1i4bSlQYCUlgLtQPoXBcNI4YkMLCbJuumbbVoHBO1HUCS-udgzeB9q690-CFzdOviHrMzzeIDUiTFO0gFQXDJK1Zo09WQcMyHIClczICs1uVEc1LoHJGdLcqToFDLlAV1Xnz3ehr3QuICL3ZbuLDpj0ecNy2NVtK4P0AAFbNnAUvqMg0AdMJqaMo3WjFa3WLeENThIFrMwdzXyn11PMyR0rJUBUmJOyGkuI8XEDzQO9MV7hn7qxQeoth79l3JzceIAzrQBnqMeesCGLYjEFAXAdggR-zrqRFB6cn4QCzpHaO389og2xEfHAl0KoV2LlXboANPZLggKNU+XANiH0Vv9EwJNPaGUptTJ0JMyayJ9jpcuqNeGwKXvAwWsxVypyHjmbeedhwHiwbLeW7DB44HIKrKASAv4gHYqmQIXEwpS2BItcmYhSKmTxkJUBNk1LlSgLXeq1CbD2mQiAdC9RMKdzpr+RmSC9GdlQZRdBNEhwjiwZPLg09Z6UAXrzLu2jV66JTqkzehisASygFk0xe9zHiOtizM+F8r5mhUnfUBqZlqRL1AMWJdTyG-zUZXKCdhKxaN-A2cmLYTIVLThwDO9Ds5MP3NLY8U5pl1gXCAJcK5FnkRWQw52uc6kbPHsCMZPCoJ+2AAbIAA)

**Comment by mocsharp** [comment]
Synchronous HTTP plugin ([source](https://sequencediagram.org/index.html#initialData=MQAgwgTgpghgLlAJieIAWc4AcDOAuAegJygEcBXKAOwGMkBLGAcwhgFsA6AewiYICg49OABsoIAOo8A1gDMRXAO4gAsjCrMoEEAFoQACQAqhgAogTI8k3pV+-LDAhCa9B1Tgsu5LCGA1EsjCIAEySMvJKquqaEPaOzq7qcCAARFIQcgrKahpMWikoOJIqcU70Lm7JKSpQODia5hBcdDg8BTBFKialCZWpNXUNAIqUlAD87Z1D-NSIdg5lFUme3r6yNABGAIyyAOwghh3SUblaPeWJ7qmHOMc5MZMHJQu9SalGpuaW1lSPAILdWZ2c5LdwrHzAABi0MhAE5YSAAKIADwQEA0IhAAGUtAA3cq1fiyLjuGCKWpcNjiWRbGgABlSACUYBsNsIVENHiYsUSSXAyRSqSBZHSYAzqjYAJIAeUeABFJViANK80nk1pUgCsrRE9GQIpgNAMxkBVDmIMuyW5dkNQlx8HEhhK-AkKh0wC2ADY6QAWRCevAAZgAfNy8OZyBtdTg0LUQABqeMAKiTAHI2IgOPzbhxEPQcA44DQ0KmU4n+Nz3V7ff6g8GuuHGVA6PRcXHEyn05ns9Jc-nC8XS0nEyAoG33PwulXvX6AyGOeGRlBKEUO2mM1mjn2C-BB2X46Px3A7AouFhgfwnTp60NwxIYMIisTtGPqHAcJOhtOa3Pg07G82UCtnGr4TrarYOk8dhXn+KjhgAajAuqIA6RRUoMeQ2iIyQegAHJqMC7AyNAdOIXabjmeY7kWJbQW6sHhmAsY0NIT48Cg9r0CILJiKOyLNuQQgkiA0CtOQEAtCAWE4TAgZ+rCyAkSQIkUuJdAcQ+SFRlAdHXv+IBNiQEBtkUUD8TQgn0MJoleBJOkwfpAAyzSoSAABkIA2Dg-LuIwCBFDQJKyPQTDiUgAA6VAQOQVBUFoICKMIaAgNY44gH8dRQGwUYAJ4jEh9DBUgABy7A6fwSE4VsuE7ERIBKeI0WxfFxIxXMDlwSAADi1BaK5CBsFgPCODlIDecNeT1dAiBvowIgfh14aSlQwhzfQABecZNXFsQwQC4YogJCAABQAJQ2jQdqQQC-AAteCrKuGcpKFQChBCgZSBJdH53cGHwmIxSGYv96U5bQ6UmJKCVJR9Qhfe+F1XQgxqmPw-3Xv9B3mYJcY9rdJgADw6DomMGbUQ1UCQ-AzeB9rI-9l4qET+1kwWJJUzTl0QcjTq6R6M61iGYbpSxRTkT224DiWh5voz36znWws4maYsbhL3goQgqYy1ciVwMl3nwOQYt-DQdBYAgiCphVXN0+IN12Hd-M-nW+kkCrCbJuumbbVoHCBYNYha-uIB5tAl0iKNcBcFBnNI-b3S05BvNXs7CtC1i4bK4gq5e+LW4aw6Q4jqByR6wb-JwMbICpjg5Bm1ASBINr7GpoEXFhdrcsMWTYikaZ2NCVQKliXZ1OwLbyfOnH3MJ3YM92xDwJQPN4gNSJMU7SAVBcMkrVmnz1bp6GmcgKVos12rW5UVL2ulyAx07ypOgUMuUDnanR+CyfWezKr3YFywJrKAd8jzQ31mNSu1dUzQAAFbNjgNrdQyBoAdGEqmRkm8tDFV3libwQ0nDNzsECGYq96qkW3jHMyR0rLDxsmpcQMBOLcW0lJT+AtfzC3PqxS+ADKL9l3NLe+x1oAv1GO-bu+ksRiCgLgYhB9l5kPXjYe0yEQDoXqJhQ+HDFan24bnTsV9+HUT3MOA8win6iNfpQD+bo07fyVn-T2hi+G9kLsHMxOsy4w0NlXMWcCEFILNCpNBw9UzLVUXqAYmiQHyPNAvKewJKz2N-A2MmLYTLOO9hwX2EB-aUiwEHEBIdS6ThMPLb+C4QBLhXFk8iuT8mBygB4kuR5l7BOAKeLAQA)

[![WM-HTTP](https://user-images.githubusercontent.com/4236590/163039864-6d008952-de66-4246-b048-11f77c83c030.png)](https://sequencediagram.org/index.html?presentationMode=readOnly#initialData=MQAgwgTgpghgLlAJieIAWc4AcDOAuAegJygEcBXKAOwGMkBLGAcwhgFsA6AewiYICg49OABsoIAOo8A1gDMRXAO4gAsjCrMoEEAFoQACQAqhgAogTI8k3pV+-LDAhCa9B1Tgsu5LCGA1EsjCIAEySMvJKquqaEPaOzq7qcCAARFIQcgrKahpMWikoOJIqcU70Lm7JKSpQODia5hBcdDg8BTBFKialCZWpNXUNAIqUlAD87Z1D-NSIdg5lFUme3r6yNABGAIyyAOwghh3SUblaPeWJ7qmHOMc5MZMHJQu9SalGpuaW1lSPAILdWZ2c5LdwrHzAABi0MhAE5YSAAKIADwQEA0IhAAGUtAA3cq1fiyLjuGCKWpcNjiWRbGgABlSACUYBsNsIVENHiYsUSSXAyRSqSBZHSYAzqjYAJIAeUeABFJViANK80nk1pUgCsrRE9GQIpgNAMxkBVDmIMuyW5dkNQlx8HEhhK-AkKh0wC2ADY6QAWRCevAAZgAfNy8OZyBtdTg0LUQABqeMAKiTAHI2IgOPzbhxEPQcA44DQ0KmU4n+Nz3V7ff6g8GuuHGVA6PRcXHEyn05ns9Jc-nC8XS0nEyAoG33PwulXvX6AyGOeGRlBKEUO2mM1mjn2C-BB2X46Px3A7AouFhgfwnTp60NwxIYMIisTtGPqHAcJOhtOa3Pg07G82UCtnGr4TrarYOk8dhXn+KjhgAajAuqIA6RRUoMeQ2iIyQegAHJqMC7AyNAdOIXabjmeY7kWJbQW6sHhmAsY0NIT48Cg9r0CILJiKOyLNuQQgkiA0CtOQEAtCAWE4TAgZ+rCyAkSQIkUuJdAcQ+SFRlAdHXv+IBNiQEBtkUUD8TQgn0MJoleBJOkwfpAAyzSoSAABkIA2Dg-LuIwCBFDQJKyPQTDiUgAA6VAQOQVBUFoICKMIaAgNY44gH8dRQGwUYAJ4jEh9DBUgABy7A6fwSE4VsuE7ERIBKeI0WxfFxIxXMDlwSAADi1BaK5CBsFgPCODlIDecNeT1dAiBvowIgfh14aSlQwhzfQABecZNXFsQwQC4YogJCAABQAJQ2jQdqQQC-AAteCrKuGcpKFQChBCgZSBJdH53cGHwmIxSGYv96U5bQ6UmJKCVJR9Qhfe+F1XQgxqmPw-3Xv9B3mYJcY9rdJgADw6DomMGbUQ1UCQ-AzeB9rI-9l4qET+1kwWJJUzTl0QcjTq6R6M61iGYbpSxRTkT224DiWh5voz36znWws4maYsbhL3goQgqYy1ciVwMl3nwOQYt-DQdBYAgiCphVXN0+IN12Hd-M-nW+kkCrCbJuumbbVoHCBYNYha-uIB5tAl0iKNcBcFBnNI-b3S05BvNXs7CtC1i4bK4gq5e+LW4aw6Q4jqByR6wb-JwMbICpjg5Bm1ASBINr7GpoEXFhdrcsMWTYikaZ2NCVQKliXZ1OwLbyfOnH3MJ3YM92xDwJQPN4gNSJMU7SAVBcMkrVmnz1bp6GmcgKVos12rW5UVL2ulyAx07ypOgUMuUDnanR+CyfWezKr3YFywJrKAd8jzQ31mNSu1dUzQAAFbNjgNrdQyBoAdGEqmRkm8tDFV3libwQ0nDNzsECGYq96qkW3jHMyR0rLDxsmpcQMBOLcW0lJT+AtfzC3PqxS+ADKL9l3NLe+x1oAv1GO-bu+ksRiCgLgYhB9l5kPXjYe0yEQDoXqJhQ+HDFan24bnTsV9+HUT3MOA8win6iNfpQD+bo07fyVn-T2hi+G9kLsHMxOsy4w0NlXMWcCEFILNCpNBw9UzLVUXqAYmiQHyPNAvKewJKz2N-A2MmLYTLOO9hwX2EB-aUiwEHEBIdS6ThMPLb+C4QBLhXFk8iuT8mBygB4kuR5l7BOAKeLAQA)

**Comment by jackschofield23** [comment]
@joshliberty @neildsouth  Can this be deleted? I thought we were replacing this with clinical review plugin

**Comment by mocsharp** [comment]
Closing as we are not planning to have a generic HTTP plug-in
