### ISSUE TITLE
Add MinIO folder and credential creation to Storage repository

### ISSUE THREAD

**Issue by jackschofield23** [Project-MONAI/monai-deploy-workflow-manager#85]
This ticket is to update the storage repository https://github.com/Project-MONAI/monai-deploy-storage to support the creation of a specific folder per workflow. Currently this repo has basic MinIO interaction functionality, we need to expand this to support both folder creation as well as credential creation for specific folders/resources.

1. Temporary credentials then need to be generated to allow access to the specified folder.
2.Create temporary credentials for MinIO (see https://docs.min.io/docs/minio-sts-quickstart-guide.html), and give them permissions to read all input artifact.

**Comment by mocsharp** [comment]
@elleyouseewhy  can we close this issue as complete?

**Comment by jackschofield23** [comment]
Closed
