### ISSUE TITLE
Create Database interaction layer 

### ISSUE THREAD

**Issue by jackschofield23** [Project-MONAI/monai-deploy-workflow-manager#86]
As part of https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/70, the workflow and task objects need to be inserted into the MongoDB database. 

The existing workflow models may need to be modified in order to support MongoDB (may need to add an ID/primary key to these models)

As this is the first ticket to implement the MongoDB database we will need to set up a connection to the database which will be a docker container within the cluster. 

For the workflow instance creation, it is required to support transactions, which means that if there is an issue, all changes can be rolled back.

**Comment by mocsharp** [comment]
@elleyouseewhy can we close this as complete?

**Comment by jackschofield23** [comment]
Closed
