### ISSUE TITLE
Post evaluators - conditional execution

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#96]
Task destinations and export destinations support conditional statements- meaning they should only be triggered when those conditional statements are met. These statements take the form of a logical string comparing variables to expected values. We need to parse those strings, replace the variables with their values, and then evaluate the string.

For details about variables that need to be supported, please see https://github.com/Project-MONAI/monai-deploy-workflow-manager/blob/develop/guidelines/mwm-workflow-spec.md#evaluators.

**Supported variables in evaluators**
the following variables should be available within conditional statements:

- DICOM tags: it should be possible to query DICOM tags of the original DICOM input. This should be accessible at context.dicom

**Support Logical Operators**

| Operator | Data type(s)|
| :----------: | :-------------: |
| == | string & Int | 
|  != | string & int |
| > | int |
| < | int |
| => | int |
| =< | int |

- Ability to use AND/OR Keywords.
- Ability to use parenthese to form logical groups.

*Examples:-*
**Single conditions clause**
```json
{
    ...task...
    "task_destinations": [
        {
            "name": "my-task-id",
            "conditions": ["{{context.dicom.tags[('0010','0040')]}} == 'F'"]
        },
    ],
    ...
}
```
**Multiple Conditions clause using AND**
```json
{
    ...task...
    "task_destinations": [
        {
            "name": "my-task-id",
            "conditions": ["{{context.dicom.tags[('0010','0040')]}} == 'F' AND {{context.executions.body_part_identifier.result.body_part}} == 'leg'"]
        },
    ],
    ...
}
```
**Multiple Conditions using AND/OR keyword with parenthese**
```json
{
    ...task...
    "task_destinations": [
        {
            "name": "my-task-id",
            "conditions": ["({{context.dicom.tags[('0010','0040')]}} == 'F' AND {{context.executions.body_part_identifier.result.body_part}} == 'leg') OR {{context.dicom.series[:].SliceThickness}} < 5"]
        },
    ],
    ...
}
```

**Acceptance criteria**
1. Given a conditional statement can have mulitple logical statements using multiple AND/OR Keywords & groups defined by parenthese WHEN all logical elements have been resolved inline with normal c# precedence rules THEN the result of the condition can be returned.
2. Given a task has a task destination with conditional statements attached WHEN all conditional statements evaluate to true THEN the task destination should be triggered
3. Given a task has an export destination with conditional statements attached WHEN all conditional statements evaluate to true THEN the export destination should be triggered
4. Given a list of conditions has multiple conditions WHEN some of the conditions evaluate to true and some of them evaluate to false THEN the entire list is considered false
5. Given a condition which uses a DICOM tag WHEN the condition evaluates to true with any of the series THEN the entire condition is considered true

**Comment by RemakingEden** [comment]
### Tests
- Task destination with condition true, task dispatch message sent
- Task destination with condition false, no task dispatch message sent
- Multiple task destinations with condition true, multiple task dispatch messages sent
- Multiple task destinations with condition false, no task dispatch messages sent
- Multiple task destinations one with condition true and one with false, task dispatch message sent

- Workflow instance status is created when any task status is dispatch or accepted
- Workflow instance is succeeded when there are no more tasks to run or tasks in a running status
- Workflow instance is failed when a condition is invalid

**Comment by mocsharp** [comment]
@elleyouseewhy can we close this as complete?
