### ISSUE TITLE
Support router tasks

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#98]
Sometimes it is necessary to provide routing capabilities without executing any task. To that end, we should support a "router" task type, which is case insensitive, to act as a router  so that its task destinations with their conditional statements can be evaluated, but no real task be executed.

These Router steps are processed only within the Workflow Manager.

A Router task's structure is as follows (for further details please see the mwm-workflow-spec) :-
`
{
  "id": "router_id",
  "description": "this is the demo router",
  "type": "router",
  "timeout_minutes": "5",
  "timeout_retries": "3",
  "task_destinations": [
    {
      "name": "my-task-one"
    },
    {
      "name": "my-task-two",
      "conditions": ["{{context.input.dicom.series.all('0010','0040')}} == 'F'"]
    }
  ]
}
`

**Comment by mocsharp** [comment]
@jackschofield23 can we close this as complete?

**Comment by jackschofield23** [comment]
Closed
