### ISSUE TITLE
Mandatory versus optional artefacts

### ISSUE THREAD

**Issue by joshliberty** [Project-MONAI/monai-deploy-workflow-manager#99]
It should be possible to define whether input artefacts are mandatory or optional. If mandatory artefacts are missing the task shouldn't be executed, and an error should be logged instead.

**Comment by jackschofield23** [comment]
This has been done as part of https://github.com/Project-MONAI/monai-deploy-workflow-manager/issues/52

**Comment by mocsharp** [comment]
@jackschofield23 is this done? can we close if so?

**Comment by jackschofield23** [comment]
Closed
